<?php
header('Content-Type: application/javascript; charset=UTF-8');
?>
(function(){
try{
var c=window.TSpamReviewConfig||{};
var words=c.words||[];var contentAction=c.contentAction||'A';var authorAction=c.authorAction||'A';var preAuditUrl=c.preAuditUrl||'';
var skipAdmin=c.skipAdmin||false;var isAdmin=c.isAdmin||false;
if(window.__TSpamReviewHooked__)return;window.__TSpamReviewHooked__=true;
var submitting=false;
function toast(msg){ try{ if(window.SM&&SM.UI&&typeof SM.UI.toast==='function'){ SM.UI.toast(msg); return; } if(window.toastr&&typeof toastr.error==='function'){ toastr.error(msg); return; } if(window.iziToast&&typeof iziToast.error==='function'){ iziToast.error({title:'提示', message: msg}); return; } if(window.Swal&&Swal.fire){ Swal.fire({icon:'error', title:'提示', text: msg, timer:2000, showConfirmButton:false}); return; } }catch(e){} var t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;top:16px;right:16px;background:rgba(0,0,0,.92);color:#fff;padding:10px 14px;border-radius:8px;z-index:2147483647;font-size:14px;line-height:1.4;box-shadow:0 4px 14px rgba(0,0,0,.3);pointer-events:none;white-space:pre-line;';document.body.appendChild(t);setTimeout(function(){t.remove();},2600);}
var CN_RE=/[\u4e00-\u9fa5]/;function hasCn(s){return CN_RE.test(s||'');}
function hitWord(s){if(!s)return false;var x=(s+'').toLowerCase();for(var i=0;i<words.length;i++){var w=(words[i]+'').toLowerCase().trim();if(!w)continue;if(x.indexOf(w)!==-1)return w;}return false;}
function pick(f){var c=f&&f.querySelector?f.querySelector('textarea[name=text],textarea[name=comment]'):null;var a=f&&f.querySelector?f.querySelector('input[name=author]'):null;var m=f&&f.querySelector?f.querySelector('input[name=mail],input[name=email]'):null;return {content:(c?c.value:((f&&f.text?f.text.value:((f&&f.comment?f.comment.value:''))))),author:(a?a.value:(f&&f.author?f.author.value:'')),mail:(m?m.value:(f&&f.mail?f.mail.value:(f&&f.email?f.email.value:'')))};}
function validateValues(v){if(skipAdmin&&isAdmin){return true;}var w=hitWord(v.content)||hitWord(v.author)||hitWord(v.mail);if(w){toast('评论失败：包含敏感词');return false;}if(!hasCn(v.content)){if(contentAction==='C'){toast('评论失败：内容需包含中文');return false;}}if(!hasCn(v.author)){if(authorAction==='C'){toast('评论失败：昵称需包含中文');return false;}}return true;}
function doPrecheck(v,callback){if(skipAdmin&&isAdmin){callback(true);return;}if(!preAuditUrl){callback(true);return;}var fd=new FormData();fd.append('text',v.content||'');fd.append('author',v.author||'');fd.append('mail',v.mail||'');fetch(preAuditUrl,{method:'POST',credentials:'same-origin',body:fd}).then(function(r){return r.json();}).then(function(res){if(res&&res.ok){callback(true);}else{var msg='评论失败，疑似包含广告信息';if(res&&res.error){msg=res.error;}else if(res&&res.reasons){msg='评论失败：'+res.reasons.join(',');}toast(msg);callback(false);}}).catch(function(){callback(true);});}
function isSubmitControl(el){ if(!el) return false; var t=(el.getAttribute&&el.getAttribute('type'))||''; t=t?t.toLowerCase():''; if(t==='submit') return true; var name=(el.getAttribute&&el.getAttribute('name'))||''; if(name==='submit') return true; if(el.matches){ if(el.matches('input[type=submit],button[type=submit]')) return true; if(el.matches('[data-submit],.submit')) return true; } return false; }
function isEmojiControl(el){ if(!el) return false; if(el.matches && el.matches('.emoji,.emojis,.smilies,.smiley,.OwO,.OwO-logo,.OwO-body,.OwO-emoji,.OwO-item,[data-emoji],[data-smilies],[data-owo]')) return true; var p=el.closest&&el.closest('.OwO,[data-emoji],[data-smilies],[data-owo],.smilies,.emoji'); return !!p; }
function fixEmojiButtons(){ try{ var btns=document.querySelectorAll('button:not([type])'); for(var i=0;i<btns.length;i++){ var b=btns[i]; if(isEmojiControl(b)){ b.setAttribute('type','button'); } } }catch(e){} }
if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded',fixEmojiButtons,{once:true}); } else { fixEmojiButtons(); }
var hasThemeHandler=false;setTimeout(function(){if(window.handleCommentSubmit||window.SM){hasThemeHandler=true;}},100);
document.addEventListener('submit',function(e){var t=e.target;if(!t||t.tagName!=='FORM')return;var c=t.querySelector&&t.querySelector('textarea[name=text],textarea[name=comment]');if(!c)return;if(t.__precheckPassed){delete t.__precheckPassed;return true;}if(submitting){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return false;}var sub=(e.submitter||document.activeElement);if(sub&&!isSubmitControl(sub)){if(isEmojiControl(sub)){e.preventDefault();e.stopPropagation();return false;}}var v=pick(t);if(!validateValues(v)){e.preventDefault();e.stopPropagation();return false;}e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();submitting=true;var btn=t.querySelector('button[type=submit],.submit');var btnText='';if(btn){btnText=btn.innerHTML;btn.disabled=true;btn.classList.add('loading');btn.innerHTML='<i class="loading-icon"></i> 检测中...';}doPrecheck(v,function(pass){if(!pass){submitting=false;if(btn){btn.disabled=false;btn.classList.remove('loading');btn.innerHTML=btnText;}return;}if(hasThemeHandler){t.__precheckPassed=true;submitting=false;if(btn){btn.disabled=false;btn.classList.remove('loading');btn.innerHTML=btnText;}btn.click();return;}var url=t.getAttribute('action')||location.href;var fd=new FormData(t);if(btn){btn.innerHTML='<i class="loading-icon"></i> 提交中...';}fetch(url,{method:'POST',credentials:'same-origin',body:fd}).then(function(r){return r.text().then(function(html){submitting=false;if(btn){btn.disabled=false;btn.classList.remove('loading');btn.innerHTML=btnText;}if(r.ok&&r.redirected){toast('评论提交成功');setTimeout(function(){location.reload();},1000);return;}if(html.indexOf('<h1>评论失败</h1>')!==-1||html.indexOf('Typecho\\Widget\\Exception')!==-1){var match=html.match(/Exception:\s*([^\n<]+)/);var msg='评论提交失败';if(match){msg=match[1].trim();if(msg.indexOf(' in ')!==-1){msg=msg.substring(0,msg.indexOf(' in ')).trim();}}toast(msg);return;}toast('评论提交成功');setTimeout(function(){location.reload();},1000);});}).catch(function(){submitting=false;if(btn){btn.disabled=false;btn.classList.remove('loading');btn.innerHTML=btnText;}toast('网络异常，请重试');});});return false;},true);
document.addEventListener('click',function(e){var el=e.target;if(!el)return; var btn=el.closest&&el.closest('button[type=submit], input[type=submit]'); if(!btn)return; var f=btn.form||el.closest&&el.closest('form'); if(f&&f.querySelector&&f.querySelector('textarea[name=text],textarea[name=comment]')){ var v=pick(f); if(!validateValues(v)){ e.preventDefault(); e.stopImmediatePropagation(); return false; } }}, true);
}catch(e){}
})();
