<?php
header('Content-Type: application/javascript; charset=UTF-8');
?>
(function(){
try{
var c=window.TSpamReviewConfig||{};
var words=c.words||[];var contentAction=c.contentAction||'A';var authorAction=c.authorAction||'A';var preAuditUrl=c.preAuditUrl||'';
if(window.__TSpamReviewHooked__)return;window.__TSpamReviewHooked__=true;
function toast(msg){ try{ if(window.SM&&SM.UI&&typeof SM.UI.toast==='function'){ SM.UI.toast(msg); return; } if(window.toastr&&typeof toastr.error==='function'){ toastr.error(msg); return; } if(window.iziToast&&typeof iziToast.error==='function'){ iziToast.error({title:'提示', message: msg}); return; } if(window.Swal&&Swal.fire){ Swal.fire({icon:'error', title:'提示', text: msg, timer:2000, showConfirmButton:false}); return; } }catch(e){} var t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;top:16px;right:16px;background:rgba(0,0,0,.92);color:#fff;padding:10px 14px;border-radius:8px;z-index:2147483647;font-size:14px;line-height:1.4;box-shadow:0 4px 14px rgba(0,0,0,.3);pointer-events:none;white-space:pre-line;';document.body.appendChild(t);setTimeout(function(){t.remove();},2600);}
var CN_RE=/[\u4e00-\u9fa5]/;function hasCn(s){return CN_RE.test(s||'');}
function hitWord(s){if(!s)return false;var x=(s+'').toLowerCase();for(var i=0;i<words.length;i++){var w=(words[i]+'').toLowerCase().trim();if(!w)continue;if(x.indexOf(w)!==-1)return w;}return false;}
function pick(f){var c=f&&f.querySelector?f.querySelector('textarea[name=text],textarea[name=comment]'):null;var a=f&&f.querySelector?f.querySelector('input[name=author]'):null;var m=f&&f.querySelector?f.querySelector('input[name=mail],input[name=email]'):null;return {content:(c?c.value:((f&&f.text?f.text.value:((f&&f.comment?f.comment.value:''))))),author:(a?a.value:(f&&f.author?f.author.value:'')),mail:(m?m.value:(f&&f.mail?f.mail.value:(f&&f.email?f.email.value:'')))};}
function ajaxPreAudit(text, author, mail){ try{ var url=preAuditUrl||((window.Typecho&&Typecho.siteUrl?Typecho.siteUrl:'')+'action/TSpamReview'); var body=new URLSearchParams(); body.set('text', text||''); body.set('author', author||''); body.set('mail', mail||''); return fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},credentials:'same-origin',body:String(body)}).then(function(r){if(!r.ok){return {ok:true,decision:'allow'};}return r.text().then(function(txt){try{return JSON.parse(txt);}catch(e){return {ok:true,decision:'allow'};}});}).catch(function(e){return {ok:true,decision:'allow'};}); }catch(e){ return Promise.resolve({ok:true,decision:'allow'}); } }
function formatReasons(reasons){ try{ if(!reasons||!reasons.length) return '系统判定违规，请注意您的言论'; var map={ sensitive:'包含敏感词汇', content_no_cn:'内容需包含中文', author_no_cn:'昵称需包含中文', baidu_block:'系统判定违规，请注意您的言论', baidu_review:'系统判定违规，请注意您的言论', baidu_review_deny:'系统判定违规，请注意您的言论', baidu_error:'系统判定违规，请注意您的言论' }; var lines=[]; for(var i=0;i<reasons.length;i++){ var k=reasons[i]; lines.push(map[k]||k); } return lines.join('\n'); }catch(e){ return '系统判定违规，请注意您的言论'; } }
function submitViaFetch(f, decision){ try{ var url=f.getAttribute('action')||location.href; var fd=new FormData(f); return fetch(url,{method:'POST',credentials:'same-origin',body:fd}).then(function(r){ if(!r.ok){ toast('评论提交失败('+r.status+')'); return; } if(decision==='hold'){ toast('评论已进入人工审核'); } else { toast('评论提交成功'); } setTimeout(function(){ try{ location.reload(); }catch(e){} }, 800); }).catch(function(){ toast('网络异常，稍后重试'); }); }catch(e){ try{ f.submit(); }catch(_){} } }
function validateValues(v){var w=hitWord(v.content)||hitWord(v.author)||hitWord(v.mail);if(w){toast('评论失败：包含敏感词');return false;}if(!hasCn(v.content)){if(contentAction==='C'){toast('评论失败：内容需包含中文');return false;}}if(!hasCn(v.author)){if(authorAction==='C'){toast('评论失败：昵称需包含中文');return false;}}return true;}
function validateForm(f){return validateValues(pick(f));}
function isSubmitControl(el){ if(!el) return false; var t=(el.getAttribute&&el.getAttribute('type'))||''; t=t?t.toLowerCase():''; if(t==='submit') return true; var name=(el.getAttribute&&el.getAttribute('name'))||''; if(name==='submit') return true; if(el.matches){ if(el.matches('input[type=submit],button[type=submit]')) return true; if(el.matches('[data-submit],.submit')) return true; } return false; }
function isEmojiControl(el){ if(!el) return false; if(el.matches && el.matches('.emoji,.emojis,.smilies,.smiley,.OwO,.OwO-logo,.OwO-body,.OwO-emoji,.OwO-item,[data-emoji],[data-smilies],[data-owo]')) return true; var p=el.closest&&el.closest('.OwO,[data-emoji],[data-smilies],[data-owo],.smilies,.emoji'); return !!p; }
function fixEmojiButtons(){ try{ var btns=document.querySelectorAll('button:not([type])'); for(var i=0;i<btns.length;i++){ var b=btns[i]; if(isEmojiControl(b)){ b.setAttribute('type','button'); } } }catch(e){} }
if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded',fixEmojiButtons,{once:true}); } else { fixEmojiButtons(); }
document.addEventListener('submit',function(e){var t=e.target;if(!t||t.tagName!=='FORM')return;var c=t.querySelector&&t.querySelector('textarea[name=text],textarea[name=comment]');if(!c)return;e.preventDefault();e.stopImmediatePropagation();var sub=(e.submitter||document.activeElement);if(sub&&!isSubmitControl(sub)){if(isEmojiControl(sub)){return false;}}var v=pick(t);if(!validateValues(v)){return false;}ajaxPreAudit(v.content,v.author,v.mail).then(function(res){if(!res){toast('网络异常，稍后重试');return;}if(res.ok===false||res.decision==='deny'){var msg=res.message||formatReasons(res.reasons||[]);toast('评论失败：'+msg);return;}var decision=(res&&res.decision)||'allow';if(decision==='hold'){toast('评论已进入人工审核');return;}submitViaFetch(t,decision);});return false;},true);
document.addEventListener('click',function(e){var el=e.target;if(!el)return; var btn=el.closest&&el.closest('button[type=submit], input[type=submit]'); if(!btn)return; var f=btn.form||el.closest&&el.closest('form'); if(f&&f.querySelector&&f.querySelector('textarea[name=text],textarea[name=comment]')){ var v=pick(f); if(!validateValues(v)){ e.preventDefault(); e.stopImmediatePropagation(); return false; } }}, true);
(function(){ var nativeSubmit=HTMLFormElement&&HTMLFormElement.prototype&&HTMLFormElement.prototype.submit; if(nativeSubmit){ HTMLFormElement.prototype.submit=function(){ try{ var f=this; if(f&&f.querySelector&&f.querySelector('textarea[name=text],textarea[name=comment]')){ var v=pick(f); if(!validateValues(v)){ toast('评论失败：不符合规范'); return; } } }catch(ex){} return nativeSubmit.apply(this, arguments); }; } })();
}catch(e){}
})();
